#!/usr/bin/env bash

# Run FEAT design files movie runs 1-5 for each participant

set -eu


### Key vars ###

basedir=/Volumes/INTENSO/Data_Of_Mice_and_Men/
design_dir=$basedir/design_files/
templates_dir=$design_dir/templates/

scans=(movie_run-1 movie_run-2 movie_run-3 movie_run-4 movie_run-5)


### Begin ###

# String for appending design file paths to
fsf_files=""

# Glob & loop subject directories
for subjdir in $(find $basedir/ -maxdepth 1 -type d -name "sub-???xxxx" | sort); do
    subj=$(basename $subjdir)
    
    echo "Starting processing of $subj"
    
    # Loop scans
    for scan in ${scans[@]}; do
        echo "Starting processing of $scan"

        # Check if FEAT dir already exists, skip if so
        featdir=$subjdir/${scan}.feat
        if [[ -d $featdir ]]; then
            echo "$featdir already exists, skipping"
            continue
        fi
        
        # Check if input data exists, warn and skip if not
	scanname=${subj}_task-${scan}_bold.nii
        indata=$subjdir/func/${scanname}
        if [[ ! -f $indata ]]; then
            echo "$indata file missing - skipping"
            continue
        fi
        
        # Run feat
        design_file=${design_dir}/${subj}_${scan}.fsf
	echo $design_file
	feat $design_file         

    done
done

